import { test, expect } from './support/bilingual-fixtures.js';
import { createSaleScenario } from '../../apps/api/tests/support/sales-factories.js';

test('seller adds ten products, prepares a ticket, and starts a distinct next sale on mobile', async ({ page, warehouse }, testInfo) => {
  test.setTimeout(90_000);
  const scenario = await createSaleScenario(warehouse.database, { stockQuantity: '5.000', standardUnitPrice: '10.0000' });
  const productIds = [scenario.product.id];
  await warehouse.database.updateTable('customer').set({ display_name: 'Tienda Rediseño' }).where('id', '=', scenario.customer.id).execute();
  await warehouse.database.updateTable('product').set({ name: 'Producto 01' }).where('id', '=', scenario.product.id).execute();
  for (let index = 2; index <= 10; index++) {
    const product = await warehouse.database.insertInto('product').values({ name: `Producto ${String(index).padStart(2, '0')}`, sku: `RED-${crypto.randomUUID()}`, category_id: scenario.category.id, unit_id: scenario.unit.id, standard_unit_price: '10.0000', low_stock_threshold: '0.000', description: null, archived_at: null }).returning('id').executeTakeFirstOrThrow();
    productIds.push(product.id);
    await warehouse.database.insertInto('inventory_balance').values({ stock_location_id: scenario.stockLocation.id, product_id: product.id, quantity: '5.000' }).execute();
  }
  const driver = await warehouse.database.selectFrom('app_user').select('username').where('id', '=', scenario.driver.id).executeTakeFirstOrThrow();
  const principal = await warehouse.login(driver.username);
  const split = principal.cookie.indexOf('=');
  await page.context().addCookies([{ name: principal.cookie.slice(0, split), value: principal.cookie.slice(split + 1), url: 'http://127.0.0.1:5173' }]);
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/sales/new');
  await page.getByRole('button', { name: /Tienda Rediseño/ }).click();
  await page.getByRole('button', { name: /Siguiente: productos/i }).click();
  for (let index = 1; index <= 10; index++) await page.getByRole('button', { name: `Agregar Producto ${String(index).padStart(2, '0')}`, exact: true }).click();
  await expect(page.getByLabel('Cantidad', { exact: true })).toHaveCount(10);
  await expect(page.getByRole('button', { name: 'Agregar Producto 01', exact: true })).toBeDisabled();
  await page.getByRole('button', { name: 'Aumentar Producto 01', exact: true }).click();
  await expect(page.getByLabel('Cantidad', { exact: true }).first()).toHaveValue('2.000');
  await page.getByRole('button', { name: 'Disminuir Producto 01', exact: true }).click();
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: testInfo.outputPath('ten-products-mobile.png'), fullPage: true });
  await page.getByRole('button', { name: 'Revisar venta', exact: true }).click();
  await expect(page.getByText('MXN 100.00', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Confirmar venta', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Ticket de venta', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Preparar ticket', exact: true }).click();
  await expect(page.getByRole('button', { name: /Descargar PDF/i })).toBeEnabled();
  await page.screenshot({ path: testInfo.outputPath('ticket-mobile.png'), fullPage: true });
  const sales = await warehouse.database.selectFrom('sale').selectAll().where('route_id', '=', scenario.route.id).execute();
  expect(sales).toHaveLength(1);
  expect(sales[0]!.total).toBe('100.00');
  const lines = await warehouse.database.selectFrom('sale_line').selectAll().where('sale_id', '=', sales[0]!.id).execute();
  expect(lines).toHaveLength(10);
  expect(lines.every((line) => line.quantity === '1.000')).toBe(true);
  const stock = await warehouse.database.selectFrom('inventory_balance').select('quantity').where('stock_location_id', '=', scenario.stockLocation.id).execute();
  expect(stock.every((balance) => balance.quantity === '4.000')).toBe(true);
  await page.getByRole('button', { name: 'Nueva venta', exact: true }).click();
  await page.getByRole('button', { name: /Tienda Rediseño/ }).click();
  await page.getByRole('button', { name: /Siguiente: productos/i }).click();
  await page.getByRole('button', { name: 'Agregar Producto 01', exact: true }).click();
  await page.getByRole('button', { name: 'Revisar venta', exact: true }).click();
  await page.getByRole('button', { name: 'Confirmar venta', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Ticket de venta', exact: true })).toBeVisible();
  const after = await warehouse.database.selectFrom('sale').select(['id', 'client_operation_id']).where('route_id', '=', scenario.route.id).execute();
  expect(after).toHaveLength(2);
  expect(new Set(after.map((sale) => sale.client_operation_id)).size).toBe(2);
  await page.goto('/sales');
  await page.getByRole('row').filter({ hasText: sales[0]!.sale_number }).getByRole('button', { name: 'Ticket de venta', exact: true }).click();
  await page.getByRole('button', { name: 'Preparar ticket', exact: true }).click();
  await expect(page.getByRole('button', { name: /Descargar PDF/i })).toBeEnabled();
  expect(await warehouse.database.selectFrom('sale').select('id').where('route_id', '=', scenario.route.id).execute()).toHaveLength(2);
});
