import { test, expect } from '@playwright/test';

test('T115 manages users and business settings on desktop and mobile', async ({page}, testInfo) => {
  await page.addInitScript(() => localStorage.setItem('warehouse-manager-language', 'en'));
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/login');
  await page.getByLabel('Username').fill('admin');
  await page.locator('input[name="password"]').fill('development-password-change-me');
  await page.getByRole('button', {name: 'Sign in', exact: true}).click();
  await expect(page).not.toHaveURL(/login/);
  await page.goto('/users');
  await page.getByRole('button', {name: 'New user', exact: true}).click();
  const name = `T115-${crypto.randomUUID().slice(0,8)}`;
  await page.getByLabel('Username', {exact: true}).fill(name);
  await page.getByLabel('Display name').fill(name);
  await page.getByLabel('Password', {exact: true}).fill('new-driver-password-123');
  await page.getByRole('button', {name: 'Save user', exact: true}).click();
  await expect(page.getByRole('alert')).toHaveText('Changes saved.');
  await page.getByRole('button', {name: `Edit ${name}`, exact: true}).click();
  await expect(page.getByLabel('Username', {exact: true})).toBeDisabled();
  await expect(page.getByLabel('Password', {exact: true})).toHaveValue('');
  await page.getByRole('combobox', {name: 'Status', exact: true}).last().click();
  await page.getByRole('option', {name: 'Inactive', exact: true}).click();
  await page.getByLabel('Reason', {exact: true}).fill('Temporary leave');
  await page.screenshot({path: testInfo.outputPath('users-desktop.png'), fullPage: true});
  await page.getByRole('button', {name: 'Save user', exact: true}).click();
  await expect(page.getByRole('alert')).toHaveText('Changes saved.');
  await page.reload();
  await page.getByRole('button', {name: `Edit ${name}`, exact: true}).click();
  await expect(page.getByRole('combobox', {name: 'Status', exact: true}).last()).toHaveText('Inactive');
  await page.setViewportSize({width: 390, height: 844});
  await page.screenshot({path: testInfo.outputPath('users-mobile.png'), fullPage: true});
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.goto('/settings');
  await page.getByLabel('Business timezone').fill('America/Tijuana');
  await page.getByLabel('Reason', {exact: true}).fill('T115 test operating timezone');
  await page.getByRole('button', {name: 'Save business settings', exact: true}).click();
  await expect(page.getByRole('alert')).toHaveText('Changes saved.');
  await page.reload();
  await expect(page.getByLabel('Business timezone')).toHaveValue('America/Tijuana');
  await page.screenshot({path: testInfo.outputPath('settings-mobile.png'), fullPage: true});
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  expect(errors).toEqual([]);
});
